const datos = [
  {
    shelterName: "Perrera de los barrios",
    email: "sosperreradelosbarrios@hotmail.com",
    address: "Lugar Ringo Rango, 21, 11370, Los Barrios, Cádiz",
    coordinates: { lat: 36.17006263581372, lng: -5.475843017196659 },
    phone: "902506893",
    web: "https://www.perreradelosbarrios.com/",
    pets: [
      {
        id: 1,
        name: "Paco",
        age: "Cachorro",
        gender: "Macho",
        size: "Pequeño",
        breed: "Chihuahua",
        color: "Blanco",
        coatLength: "Corto",
        city: "Cádiz",
        description:
          "Paco es un cachorrito de aproximadamente 3 meses, alguien lo abandonó en la puerta de la protectora. Es muy cariñoso y le encanta estar en brazos.",
      },
      {
        id: 2,
        name: "Nefer",
        age: "Cachorro",
        gender: "Hembra",
        size: "Pequeño",
        breed: ["Labrador", "Golden retriever"],
        color: "Marrón",
        coatLength: "Corto",
        city: "Cádiz",
        description:
          "Es una perrita mestiza que desde que está en el refugio nadie a preguntado por ella. Es muy cariñosa y juguetona, le encanta estar con otros perros.",
      },
      {
        id: 3,
        name: "Bluey",
        age: "Adulto",
        gender: "Macho",
        size: "Mediano",
        breed: "Bodeguero",
        color: ["Blanco", "Marrón", "Negro"],
        coatLength: "Corto",
        city: "Cádiz",
        description:
          "Bluey es un perrito adulto muy tranquilo y sociable. Es ideal para personas tranquilas y además le encantan los niños.",
      },
    ],
  },
  {
    shelterName: "El arca de Noé",
    email: "elarcadenoecordoba@gmail.com",
    address: "C. Pintor, 1, 14650 Bujalance, Córdoba",
    coordinates: { lat: 37.897315296200176, lng: -4.3811522018836255 },
    phone: "917237835",
    web: "https://arcanoecordoba.es/",
    pets: [
      {
        id: 4,
        name: "Conan",
        age: "Adulto",
        gender: "Macho",
        size: "Grande",
        breed: ["Pastor alemán", "Golden retriever"],
        color: ["Negro", "Marron"],
        coatLength: "Largo",
        city: "Córdoba",
        description:
          "Conan es una mezcla de pastor alemán extremadamente social. Es bueno con otros perros y niños. Al ser adulto es mucho más tranquilo pero le encanta correr por el parque",
      },
      {
        id: 5,
        name: "Suri",
        age: "Joven",
        gender: "Macho",
        size: "Mediano",
        breed: "Podenco",
        color: "Marrón",
        coatLength: "Corto",
        city: "Córdoba",
        description:
          "Podenco muy juegueton y cariñoso. No se lleva bien con los gatos pero le encatan los niños. ",
      },
      {
        id: 6,
        name: "Deila",
        age: "Adulto",
        gender: "Hembra",
        size: "Grande",
        breed: "Border collie",
        color: ["Marrón", "Blanco"],
        coatLength: "Largo",
        city: "Córdoba",
        description:
          "Deila fue encontrada en la carretera de Córdoba en el mes de Agosto. Ya está desparasitada. Es un poco miedosa pero muy buena con otros perros y gatos. ",
      },
      {
        id: 7,
        name: "Rocky",
        age: "Adulto",
        gender: "Macho",
        size: "Grande",
        breed: ["Pastor alemán", "Corgi galés"],
        color: ["Negro", "Marron"],
        coatLength: "Largo",
        city: "Córdoba",
        description:
          "Rocky fue devuelto a las dos semanas de ser adoptado por no llevarse bien con otros perros. Es muy noble y cariñoso pero necesita tiempo para adaptarse.",
      },
    ],
  },
  {
    shelterName: "Fundacion trifolium",
    email: "fundaciontrifolium@gmail.com",
    address: "Passeig del Pitort, 25, 08860 Castelldefels, Barcelona",
    coordinates: { lat: 41.269533983313025, lng: 1.9695498865081797 },
    phone: "932786634",
    pets: [
      {
        id: 8,
        name: "Canela",
        age: "Cachorro",
        gender: "Macho",
        size: "Pequeño",
        breed: "Coker spaniel",
        color: ["Blanco", "Marrón"],
        coatLength: "Mediano",
        city: "Barcelona",
        description:
          "Cachorrito de 4 meses, un poco miedosa pero está empezando a socializar correctamente en los paseos y a buscar mismos entre la gente. Lleva al día todas sus vacunas y está esterillizado.",
      },
      {
        id: 9,
        name: "Pitu",
        age: "Cachorro",
        gender: "Macho",
        size: "Grande",
        breed: ["Pit bull", "Labrador"],
        color: ["Blanco", "Marrón"],
        coatLength: "Corto",
        city: "Barcelona",
        description:
          "El dueño de Pitu quería sacrificarlo por tener lishmaniosis, una enfermedad que con medicación se puede controlar y llevar una vida muy normal. Es muy sociable y le encantan los niños.",
      },
      {
        id: 10,
        name: "Lucky",
        age: "Joven",
        gender: "Macho",
        size: "Grande",
        breed: "Galgo",
        color: "Negro",
        coatLength: "Corto",
        city: "Barcelona",
        description:
          "Galgo de 3 años, muy tranquilo y un poco miedoso. Se está adaptando de maravilla a convivir con otros perros.",
      },
    ],
  },
  {
    shelterName: "Zarpas y Colmillos",
    email: "contacto@zarpasycolmillos.es",
    address: "Calle Dr. Espina, 39, 28019, Madrid",
    coordinates: { lat: 40.387485277353974, lng: -3.7288517000000008 },
    phone: "848171717",
    web: "https://www.zarpasycolmillos.es/",
    pets: [
      {
        id: 11,
        name: "Buli",
        age: "Adulto",
        gender: "Macho",
        size: "Mediano",
        breed: "Bulldog inglés",
        color: ["Blanco", "Marrón"],
        coatLength: "Corto",
        city: "Madrid",
        description:
          "Buli tiene ya 10 años, lleva mucho tiempo con nosotros y queremos encontrarle una familia que pueda hacerle feliz en sus últimos años. Es extremadamente cariñoso y bueno.",
      },
      {
        id: 12,
        name: "Piña",
        age: "Adulto",
        gender: "Macho",
        size: "Mediano",
        breed: ["Bulldog francés", "Boston terrier"],
        color: ["Negro", "Blanco"],
        coatLength: "Corto",
        city: "Madrid",
        description:
          "Piña lleva muchos años con nosotros. Se pone un poco nervioso con la gente que no conoce y no le gustan las aglomeraciones. Necesita una casa con mucha tranquilidad. ",
      },
      {
        id: 13,
        name: "Kimba",
        age: "Joven",
        gender: "Hembra",
        size: "Grande",
        breed: ["Border collie", "Golden retriever"],
        color: ["Negro", "Blanco"],
        coatLength: "Largo",
        city: "Madrid",
        description:
          "Kimba es una mezcla de Border Collie, creemos que tiene unos 4 años de edad. Es muy dulce y jugetona. Le encanta dar paseos muy largos por la montaña.",
      },
      {
        id: 14,
        name: "Sherpi",
        age: "Adulto",
        gender: "Macho",
        size: "Grande",
        breed: "Pastor alemán",
        color: ["Negro", "Marrón"],
        coatLength: "Medio",
        city: "Madrid",
        description:
          "Sherpi viene de una casa donde sufría maltrato animal, eso hace que tenga un carácter algo especial. Al principio es miedoso y desconfiado pero una vez se acostumbra es muy mimoso y tranquilo.",
      },
      {
        id: 15,
        name: "Kiara",
        age: "Cachorro",
        gender: "Hembra",
        size: "Pequeño",
        breed: ["Jack Russell", "Yorkshire Terrier"],
        color: ["Blanco", "Marrón"],
        coatLength: "Corto",
        city: "Madrid",
        description:
          "Kiara es una de los tres cachorros abandonados en una caja de fruta en medio de una finca. A sus hermanitos ya los han adoptado. Está totalmente desparasitada, vacunada y lista para conocer a su nueva familia.",
      },
    ],
  },
];

export default datos;
