const datos = [
    {
      shelterName: "sosperreradelosbarrios",
      email: "sosperreradelosbarrios@hotmail.com",
      address: "Lugar Ringo Rango, 21, 11370, Los Barrios, Cádiz",
      coordinates: { lat: 36.17006263581372, lng: -5.475843017196659 },
      city: "Cádiz",
      phone: "902506893",
      web: "https://www.perreradelosbarrios.com/",
      pets: [
        {
          id: 1,
          name: "Paco",
          age: "Cachorro",
          gender: "Macho",
          size: "Pequeño",
          breed: "Chihuahua",
          color: "Blanco",
          coatLength: "Corto",
          city: "Cádiz",
          
        },
        {
          id: 2,
          name: "Nefer",
          age: "Cachorro",
          gender: "Hembra",
          size: "Pequeño",
          breed: ["Labrador", "Golden retriever"],
          color: "Marrón",
          coatLength: "Corto",
          city: "Cádiz",
          
        },
        {
          id: 3,
          name: "Bluey",
          age: "Adulto",
          gender: "Macho",
          size: "Mediano",
          breed: "Bodeguero",
          color: ["Blanco", "Marrón", "Negro"],
          coatLength: "Corto",
          city: "Cádiz",
          
        },
      ],
    },
    {
      shelterName: "El arca de Noé",
      email: "elarcadenoecordoba@gmail.com",
      address: "C. Pintor, 1, 14650 Bujalance, Córdoba",
      coordinates: { lat: 37.897315296200176, lng: -4.3811522018836255 },
      city: "Córdoba",
      phone: "917237835",
      web: "https://arcanoecordoba.es/",
      pets: [
        {
          id: 4,
          name: "Conan",
          age: "Adulto",
          gender: "Macho",
          size: "Grande",
          breed: ["Pastor alemán", "Golden retriever"],
          color: ["Negro", "Marron"],
          coatLength: "Largo",
          city: "Córdoba",
          
        },
        {
          id: 5,
          name: "Suri",
          age: "Joven",
          gender: "Macho",
          size: "Mediano",
          breed: "Podenco",
          color: "Marrón",
          coatLength: "Corto",
          city: "Córdoba",
          
        },
        {
          id: 6,
          name: "Deila",
          age: "Adulto",
          gender: "Hembra",
          size: "Grande",
          breed: "Border collie",
          color: ["Marrón", "Blanco"],
          coatLength: "Largo",
          city: "Córdoba",
          
        },
        {
          id: 7,
          name: "Rocky",
          age: "Adulto",
          gender: "Macho",
          size: "Grande",
          breed: ["Pastor alemán", "Corgi galés"],
          color: ["Negro", "Marron"],
          coatLength: "Largo",
          city: "Córdoba",
          
        },
      ],
    },
    {
      shelterName: "Fundacion trifolium",
      email: "fundaciontrifolium@gmail.com",
      address: "Passeig del Pitort, 25, 08860 Castelldefels, Barcelona",
      coordinates: { lat: 41.269533983313025, lng: 1.9695498865081797 },
      city: "Barcelona",
      phone: "932786634",
      pets: [
        {
          id: 8,
          name: "Canela",
          age: "Cachorro",
          gender: "Macho",
          size: "Pequeño",
          breed: "Coker spaniel",
          color: ["Blanco","Marrón"],
          coatLength: "Mediano",
          city: "Barcelona",
          
        },
        {
          id: 9,
          name: "Pitu",
          age: "Cachorro",
          gender: "Macho",
          size: "Grande",
          breed: ["Pit bull", "Labrador"],
          color: ["Blanco","Marrón"],
          coatLength: "Corto",
          city: "Barcelona",
          
        },
        {
          id: 10,
          name: "Lucky",
          age: "Joven",
          gender: "Macho",
          size: "Grande",
          breed: "Galgo",
          color: "Negro",
          coatLength: "Corto",
          city: "Barcelona",
          
        },
      ],
    },
    {
      shelterName: "Zarpas y Colmillos",
      email: "contacto@zarpasycolmillos.es",
      address: "Calle Dr. Espina, 39, 28019, Madrid",
      coordinates: { lat: 40.387485277353974, lng: -3.7288517000000008 },
      city: "Madrid",
      phone: "848171717",
      web: "https://www.zarpasycolmillos.es/",
      pets: [
        {
          id: 11,
          name: "Buli",
          age: "Adulto",
          gender: "Macho",
          size: "Mediano",
          breed: "Bulldog inglés",
          color: ["Blanco", "Marrón"],
          coatLength: "Corto",
          city: "Barcelona",
          
        },
        {
          id: 12,
          name: "Piña",
          age: "Adulto",
          gender: "Macho",
          size: "Mediano",
          breed: ["Bulldog francés", "Boston terrier"],
          color: ["Negro", "Blanco"],
          coatLength: "Corto",
          city: "Barcelona",
          
        },
        {
          id: 13,
          name: "Kimba",
          age: "Joven",
          gender: "Hembra",
          size: "Grande",
          breed: ["Border collie", "Golden retriever"],
          color: ["Negro", "Blanco"],
          coatLength: "Largo",
          city: "Barcelona",
          
        },
        {
          id: 14,
          name: "Sherpi",
          age: "Adulto",
          gender: "Macho",
          size: "Grande",
          breed: "Pastor alemán",
          color: ["Negro", "Marrón"],
          coatLength: "Medio",
          city: "Barcelona",
          
        },
        {
          id: 15,
          name: "Kiara",
          age: "Cachorro",
          gender: "Hembra",
          size: "Pequeño",
          breed: ["Jack Russell", "Yorkshire Terrier"],
          color: ["Blanco", "Marrón"],
          coatLength: "Corto",
          city: "Barcelona",
          
        },
      ],
    },
  ];
  
  export default datos;